export const coffeeList = [
  {
    id: '1',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 990,
    tags: ['TRADICIONAL'],
    src:'/src/assets/coffees/expresso-tradicional.png',
    quantity: 0,
  },
  {
    id: '2',
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 870, 
    tags: ['TRADICIONAL'],
    src:'/src/assets/coffees/expresso-americano.png',
    quantity: 0,
  },
  {
    id: '3',
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 1150,
    tags: ['TRADICIONAL'],
    src:'/src/assets/coffees/expresso-cremoso.png',
    quantity: 0,
  },
  {
    id: '4',
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 990,
    tags: ['TRADICIONAL', 'GELADO'],
    src:'/src/assets/coffees/expresso-gelado.png',
    quantity: 0,
  },
  {
    id: '5',
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 870,
    tags: ['TRADICIONAL', 'COM LEITE'],
    src:'/src/assets/coffees/cafe-com-leite.png',
    quantity: 0,
  },
  {
    id: '6',
    name: 'Latte',
    description: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 990,
    tags: ['TRADICIONAL', 'COM LEITE'],
    src:'/src/assets/coffees/latte.png',
    quantity: 0,
  },
  {
    id: '7',
    name: 'Capuccino',
    description: 'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 1020,
    tags: ['TRADICIONAL', 'COM LEITE'],
    src:'/src/assets/coffees/capuccino.png',
    quantity: 0,
  },
  {
    id: '8',
    name: 'Macchiato',
    description: 'Café expresso misturado com um pouco de leite quente e espuma',
    price: 1020,
    tags: ['TRADICIONAL', 'COM LEITE'],
    src:'/src/assets/coffees/macchiato.png',
    quantity: 0,
  },
  {
    id: '9',
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 1020,
    tags: ['TRADICIONAL', 'COM LEITE'],
    src:'/src/assets/coffees/mocaccino.png',
    quantity: 0,
  },
  {
    id: '10',
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 1590,
    tags: ['ESPECIAL', 'COM LEITE'],
    src:'/src/assets/coffees/chocolate-quente.png',
    quantity: 0,
  },
  {
    id: '11',
    name: 'Cubano',
    description: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 1020,
    tags: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    src:'/src/assets/coffees/cubano.png',
    quantity: 0,
  },
  {
    id: '12',
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 1020,
    tags: ['ESPECIAL'],
    src:'/src/assets/coffees/havaiano.png',
    quantity: 0,
  },
  {
    id: '13',
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 1790,
    tags: ['ESPECIAL'],
    src:'/src/assets/coffees/arabe.png',
    quantity: 0,
  },
  {
    id: '14',
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 2050,
    tags: ['ESPECIAL', 'ALCOÓLICO'],
    src:'/src/assets/coffees/irlandes.png',
    quantity: 0,
  },
] 